cache:
  directories:
    - $HOME/.cache/rebar3
install: true
language: erlang
notifications:
  email: false
otp_release:
  - 22.1
  - 21.0.3
  - 20.3
  - 19.3
script: "make travis"
services:
  - cassandra
sudo: required
