name: Erlang CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lpgauth/erlang-scylla:26.2.2-5.2-amd64
    steps:
    - uses: actions/checkout@v1
    - name: Start Scylla
      run: |
        python3 /docker-entrypoint.py&
        sleep 30
    - name: Set Path
      run: |
        echo "/usr/local/lib/erlang/bin" >> $GITHUB_PATH
    - name: Compile
      run: make compile
    - name: Run xref
      run: make xref
    - name: Run eunit
      run: make eunit
    - name: Run dialyzer
      run: make dialyzer
